Increase blocksize of dd imaging to 4 MiB for nearly 3x speedup

diff --git a/hybris-installer/META-INF/com/google/android/update-binary b/hybris-installer/META-INF/com/google/android/update-binary
--- a/hybris-installer/META-INF/com/google/android/update-binary
+++ b/hybris-installer/META-INF/com/google/android/update-binary
@@ -152,14 +152,14 @@ umount /vendor &
 
 if [ "$FORCE_REINSTALL" = "0" ]; then
 	log "Backing up droid-boot image..."
-	dd if=/dev/block/bootdevice/by-name/boot of=$ROOT/boot/droid-boot.img
+	dd if=/dev/block/bootdevice/by-name/boot of=$ROOT/boot/droid-boot.img bs=4m
 elif [ -f /tmp/droid-boot.img ]; then
 	log "Moving back droid-boot image..."
 	mv /tmp/droid-boot.img $ROOT/boot/
 fi
 
 log "Writing hybris-boot image..."
-dd if=$ROOT/boot/hybris-boot.img of=/dev/block/bootdevice/by-name/boot || abort 11 "Couldn't write Hybris boot image!"
+dd if=$ROOT/boot/hybris-boot.img of=/dev/block/bootdevice/by-name/boot bs=4m || abort 11 "Couldn't write Hybris boot image!"
 
 log "Symlinking boot images to /sdcard..."
 ln -s $ROOT/boot/droid-boot.img /sdcard/
